/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Properties of an impact claim
 */
export interface HypercertClaimdata {
  /**
   * Scopes of impact
   */
  impactScopes: string;
  /**
   * Scopes of work
   */
  workScopes: string;
  /**
   * Describes the asset to which this token represents
   */
  impactTimeframe: number[];
  /**
   * Describes the asset to which this token represents
   */
  workTimeframe: number[];
  /**
   * Describes the asset to which this token represents
   */
  contributors: string[];
  [k: string]: unknown;
}
