// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tKtnZiEMup1PmF99tS3Jhx
// Component: Nv7cSj-s9F
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_hypercerts_core.module.css"; // plasmic-import: tKtnZiEMup1PmF99tS3Jhx/projectcss
import sty from "./PlasmicWorkScopeChip.module.css"; // plasmic-import: Nv7cSj-s9F/css

export type PlasmicWorkScopeChip__VariantMembers = {};
export type PlasmicWorkScopeChip__VariantsArgs = {};
type VariantPropType = keyof PlasmicWorkScopeChip__VariantsArgs;
export const PlasmicWorkScopeChip__VariantProps = new Array<VariantPropType>();

export type PlasmicWorkScopeChip__ArgsType = {
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicWorkScopeChip__ArgsType;
export const PlasmicWorkScopeChip__ArgProps = new Array<ArgPropType>("children");

export type PlasmicWorkScopeChip__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultWorkScopeChipProps {
  children?: React.ReactNode;
  className?: string;
}

const __wrapUserFunction = globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicWorkScopeChip__RenderFunc(props: {
  variants: PlasmicWorkScopeChip__VariantsArgs;
  args: PlasmicWorkScopeChip__ArgsType;
  overrides: PlasmicWorkScopeChip__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "feature-releases",
          value: args.children,
          className: classNames(sty.slotTargetChildren),
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicWorkScopeChip__OverridesType, DescendantsType<T>>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWorkScopeChip__VariantsArgs;
    args?: PlasmicWorkScopeChip__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicWorkScopeChip__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<PlasmicWorkScopeChip__ArgsType, ReservedPropsType> &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(props: T & StrictProps<T, PropsType>) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicWorkScopeChip__ArgProps,
          internalVariantPropNames: PlasmicWorkScopeChip__VariantProps,
        }),
      [props, nodeName],
    );

    return PlasmicWorkScopeChip__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWorkScopeChip";
  } else {
    func.displayName = `PlasmicWorkScopeChip.${nodeName}`;
  }
  return func;
}

export const PlasmicWorkScopeChip = Object.assign(
  // Top-level PlasmicWorkScopeChip renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicWorkScopeChip
    internalVariantProps: PlasmicWorkScopeChip__VariantProps,
    internalArgProps: PlasmicWorkScopeChip__ArgProps,
  },
);

export default PlasmicWorkScopeChip;
/* prettier-ignore-end */
